### ISSUE TITLE
isSupported() returns false even if coloring actually works

### ISSUE THREAD

**Issue by PunchyRascal** [kevinlebrun/colors.php#11]
I tried to use this module on windows and found that if I override the isSupported() method to return true, the coloring works just fine, but otherwise the library thinks that coloring is not supported and so does not color the output.

**Comment by PunchyRascal** [comment]
Also, if I override the method with the linked code from symfony, it works ok, too.
https://github.com/symfony/Console/blob/master/Output/StreamOutput.php#L95-L102

**Comment by yakatz** [comment]
You can always use `$c->setForceStyle(true);` to override the detection code.

**Comment by kevinlebrun** [comment]
I just updated the underlying detection code. It should work the same way as for Symfony Console component.
